server:
  port: ${SERVER_PORT:7001}

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/niteshthakur498/sp-config-provider}
          username: ${CONFIG_REPO_USERNAME:test-username}
          password: ${CONFIG_REPO_TOKEN:test-token}
          clone-on-start: true
          search-paths: ${CONFIG_SEARCH_PATHS:{application}}
          #default-label: ${CONFIG_GIT_BRANCH:main}
          #label: master
        #native:
          #search-locations: classpath:/configurations
          
# Eureka registration (optional if discovery is enabled)
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:true}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,refresh,busrefresh}

