spring:
  application:
    name: expense-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:10.202.233.116}:5432/test_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_USER_PWD:postgres}
    driver-class-name: org.postgresql.Driver
    jpa:
      # Set ddl-auto to 'none' to disable automatic schema generation by Hibernate
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
#  datasource:
#    url: jdbc:h2:file:./data/mydb;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console   # optional, defaults to /h2-console

  liquibase:
    default-schema: ${SERVICE_SCHEMA:public}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:7001}


server:
  port: ${SERVER_PORT:2021}



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0


management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health, info, prometheus, metrics}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:always}