spring:
  application:
    name: expense-replica-service
  data:
    mongodb:
      user: ${MONGODB_USER:root}
      password: ${MONGODB_USER_PWD:password}
      uri: mongodb://${MONGODB_HOST:localhost}:27017/${MONGODB_COLLECTION:replicatedexpense}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:9092
    consumer:
      group-id: expense-consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  liquibase:
    default-schema: ${SERVICE_SCHEMA:public}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:7001}


server:
  port: ${SERVER_PORT:2041}



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0


management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health, info, prometheus, metrics}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:always}